// examples/vue3/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Editor } from '@kosmotema/bytemd-vue-next'
import gfm from '@kosmotema/bytemd-plugin-gfm'
import '@kosmotema/bytemd/dist/index.css'

let content = ref('')

const plugins = [gfm()]

const handleChange = (v: string) => {
  content.value = v
}
</script>

<template>
  <main>
    <Editor :value="content" :plugins="plugins" @change="handleChange" />
  </main>
</template>

<style>
#app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  font-weight: normal;
}
</style>

// examples/react/src/App.tsx
import './App.css'
import pluginGfm from '@kosmotema/bytemd-plugin-gfm'
import { Editor } from '@kosmotema/bytemd-react'
import '@kosmotema/bytemd/dist/index.css'
import React, { useMemo, useState } from 'react'

function App() {
  const [value, setValue] = useState('')
  const plugins = useMemo(() => [pluginGfm()], [])

  return (
    <div className="App">
      <Editor
        value={value}
        plugins={plugins}
        uploadImages={async (files) => {
          // upload images here
          return [
            {
              url: 'https://picsum.photos/200/300',
            },
          ]
        }}
        onChange={(v) => {
          setValue(v)
        }}
      />
    </div>
  )
}

export default App
